# Generated by Django 2.0.4 on 2019-05-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='selectGeneration',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Seed.GenerationInfo'),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='selectRole',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Seed.RoleInfo'),
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='selectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seed.SeedInfo'),
        ),
    ]
