# Generated by Django 2.0.4 on 2019-05-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seed', '0002_auto_20190514_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationinfo',
            name='selectRole',
            field=models.ForeignKey(default='buy', on_delete=django.db.models.deletion.CASCADE, to='Seed.RoleInfo'),
        ),
    ]
