# Generated by Django 2.0.4 on 2019-05-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seed', '0004_auto_20190514_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailinfo',
            old_name='selectGeneration',
            new_name='generation',
        ),
        migrations.RenameField(
            model_name='detailinfo',
            old_name='selectRole',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='generationinfo',
            old_name='selectType',
            new_name='type1',
        ),
        migrations.RemoveField(
            model_name='detailinfo',
            name='selectType',
        ),
        migrations.RemoveField(
            model_name='generationinfo',
            name='selectRole',
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Seed.SeedInfo'),
        ),
        migrations.AddField(
            model_name='generationinfo',
            name='role1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Seed.RoleInfo'),
        ),
    ]
