# Generated by Django 2.0.4 on 2019-05-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seed', '0006_auto_20190515_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfo',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
