# Generated by Django 2.0.4 on 2019-05-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seed', '0007_auto_20190515_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinfo',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Seed.RoleInfo'),
        ),
    ]
